name: Front Web CI

on:
  push:
    branches: ["develop"]
    paths:
      - "FRONT-WEB/**"
      - ".github/workflows/node.js.yml"
  pull_request:
    branches: ["develop"]
    paths:
      - "FRONT-WEB/**"
      - ".github/workflows/node.js.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]  # mets les versions que tu veux tester

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: FRONT-WEB/vinyl-club/package-lock.json

      - name: Install
        working-directory: FRONT-WEB
        run: npm ci

      - name: Test
        working-directory: FRONT-WEB
        run: npm test --if-present -- --ci

      - name: Build
        working-directory: FRONT-WEB
        run: npm run build --if-present
